language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
matrix:
  allow_failures:
    - python:
       - "2.6"
    - python:
       - "pypy"
    - python:
       - "3.2"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: nosetests --verbose --with-coverage --cover-package=coursera

after_success:
  coveralls
